
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hh123456

  mqtt:
    send:
    # 服务器连接地址，如果有多个，用逗号隔开
    host: tcp://localhost:1883
    # 连接服务器默认客户端ID
    clientId: mqtt_client_id_001
    # 默认的消息推送主题，实际可在调用接口时指定
    topic: testapp
    # 用户名
    username: admin
    # 密码
    password: 123456
    # 连接超时
    timeout: 30
    # 心跳
    keepalive: 30


Logging:
  level:
    com.wms: debug